### ISSUE TITLE
Why not just use shared_ptr?

### ISSUE THREAD

**Issue by skabbes** [jrandom/SmartObject#1]
Correct me if I'm wrong, but this code seems to be trying to improve the cache characteristics of `shared_ptr`by allocating the the control block alongside the object itself.

However, cppreference.com points out that using `make_shared` actually does this too, all without being intrusive.

Taken from http://en.cppreference.com/w/cpp/memory/shared_ptr

> When shared_ptr is created by calling std::make_shared or std::allocate_shared, the memory for both the control block and the managed object is created with a single allocation. The managed object is constructed in-place in a data member of the control block. When shared_ptr is created via one of the shared_ptr constructors, the managed object and the control block must be allocated separately. In this case, the control block stores a pointer to the managed object.

Feel free to correct me if I'm wrong, but just in case you weren't aware of that optimization - wanted to let you know.

**Comment by jrandom** [comment]
I wasn't fully versed in std::make_shared when I originally wrote this object, but my local version contains more that just the refcount. I had to pull those parts for this public repository because my personal toolkit is all sorts of incomplete and not for public consumption.

So... yeah, this object is a bit more useless that originally intended.
